### ISSUE TITLE
How to use with MacOS and large file support

### ISSUE THREAD

**Issue by shantur** [jslegendre/ACPIPatcher#1]
Interesting work here.

I am interested to know how you could use the Dxe with MacOS to perform patches on every boot?
Secondly, I was looking at the code to see if it could handle a 136 KB SSDT aml file for patching GPU rom in MacOS?

Thanks

**Comment by jslegendre** [comment]
If you are on a Hackintosh both Clover and OpenCore have folders for UEFI drivers. On Apple hardware, you will need to install a bootloader (rEFInd). ACPIPatcher should handle your SSDT just fine.

**Comment by shantur** [comment]
Awesome. Thanks.
